# Generated by Django 3.2.6 on 2021-08-09 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210809_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='author',
            field=models.ForeignKey(help_text='Select the author of this blog post', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='blog.blogauthor'),
        ),
        migrations.AlterField(
            model_name='blogdetailpage',
            name='category',
            field=models.ForeignKey(help_text='Select the category of this blog post', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='blog.blogcategory'),
        ),
    ]
