# Generated by Django 3.2.6 on 2021-08-10 23:48

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_blogdetailpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='content',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.TextBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'image', 'code', 'blockquote'], template='blocks/rich-text-block.html')), ('code', wagtail.core.blocks.StructBlock([('language', wagtail.core.blocks.ChoiceBlock(choices=[('python', 'python'), ('javascript', 'javascript'), ('react', 'react'), ('djang', 'django'), ('html', 'html'), ('css', 'css'), ('markup', 'markup'), ('arduino', 'arduino'), ('matlab', 'matlab'), ('c++', 'c++'), ('c', 'c'), ('sql', 'sql'), ('vhdl', 'vhdl'), ('verilog', 'verilog')])), ('code', wagtail.core.blocks.TextBlock(help_text='Type your code here or copy and paste it from your editor'))])), ('image', wagtail.images.blocks.ImageChooserBlock())]),
        ),
    ]
